wget wwtweb.blob.core.windows.net/docs/images/BlankCollection.bmp
wget wwtweb.blob.core.windows.net/docs/images/Spitzer1.jpg
wget wwtweb.blob.core.windows.net/docs/images/Spitzer2.jpg
wget wwtweb.blob.core.windows.net/docs/images/Spitzer3.jpg
wget wwtweb.blob.core.windows.net/docs/images/Spitzer4.jpg
wget wwtweb.blob.core.windows.net/docs/images/PlaceFomalhaut.bmp
wget wwtweb.blob.core.windows.net/docs/images/NoChange.jpg
wget wwtweb.blob.core.windows.net/docs/images/Rotation45.jpg
wget wwtweb.blob.core.windows.net/docs/images/PlaceRotation45.jpg
wget wwtweb.blob.core.windows.net/docs/images/ZoomLevel0p2466.jpg
wget wwtweb.blob.core.windows.net/docs/images/ZoomLevel10.jpg
wget wwtweb.blob.core.windows.net/docs/images/PlaceOpactity25.jpg
wget wwtweb.blob.core.windows.net/docs/images/ImageOffsetpp1pp2.jpg
wget wwtweb.blob.core.windows.net/docs/images/MinimalTour.bmp
wget wwtweb.blob.core.windows.net/docs/images/CommunityThumbnail.bmp
wget wwtweb.blob.core.windows.net/docs/images/GotoNGC117.jpg
wget wwtweb.blob.core.windows.net/docs/images/Horsehead1.jpg
wget wwtweb.blob.core.windows.net/docs/images/Horsehead2.bmp
wget wwtweb.blob.core.windows.net/docs/images/HorseheadInWindows.jpg
